### PR TITLE
Version bumps

### PR DESCRIPTION
**Pull request by strangeglyph**
And here is the second PR, bumping and unpinning packages (commit based on top of #10, so that one should get merged first)

### CODE REVIEW

**Comment by cbourjau** [comment]
Thanks again! Are you also interested in tackling the nom update in a dedicated PR?

**Comment by strangeglyph** [comment]
Absolutely, I'm on it! There's some bugs in it still, not every test passes, so I'll need to do some debugging first

**Comment by cbourjau** [comment]
Feel free to open a PR already even if the tests don't pass, yet!

**Comment by strangeglyph** [comment]
I have rebased #9 and will keep that PR up to date with the nom changes

**Pull request merged**
